Refactoring cache to use Class [single-responsibiliy principle]
GCES-Pydemic/pydemic-ui pull request #42
Opened 2020-11-25 16:27 UTC by guilhermedelyra

2020-11-25 23:09 UTC, BordaLorde requested changes

2020-11-25 23:09 UTC, BordaLorde commented on pydemic_ui/info.py
> +from pydemic import Cache
Please revert these changes

2020-11-25 23:09 UTC, BordaLorde commented on pydemic_ui/info.py
> +        return Cache.TTL(key, timeout=ttl, **kwargs)(fn)
Please revert these changes

2020-11-25 23:57 UTC, guilhermedelyra commented on pydemic_ui/info.py
> +        return Cache.TTL(key, timeout=ttl, **kwargs)(fn)
Done!

2020-11-25 23:58 UTC, guilhermedelyra commented on pydemic_ui/info.py
> +from pydemic import Cache
Done

2020-11-25 23:59 UTC, guilhermedelyra commented
Everything's working properly, I guess.

2020-11-26 00:00 UTC, BordaLorde approved these changes

2020-11-26 17:26 UTC, merged